version: '3.8'  
services:

  sqlserver:
    image: "mcr.microsoft.com/azure-sql-edge:latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "1234"
      MSSQL_PID": "Express"
    ports:
      - "1433:1433"

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/posgresql/data
  
  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_ROOT_PASSWORD: 1234 
    ports:
      - 3306:3306
    volumes:
      - postgres-data:/var/lib/mysql

volumes:
  postgres-data:
    driver: local