apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simpleapi
spec:
  project: default
  source:
    repoURL: https://github.com/doniyorniyozov/kubernetes.git
    targetRevision: HEAD
    path: k8s/environments/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true #automatically create namespace if it os not there
    automated:
      selfHeal: true #don't let manual kubectl apply
      prune: true #deletes deployment if config is removed

# ArgoCD will theck every 3 minutes for the changes in git repo
