apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: simpleapi
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/doniyorniazov/kubernetes
        revision: master
        directories:
          - path: k8s/environments/*
  template:
    metadata:
      name: "{{path.basename}}"
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/doniyorniazov/kubernetes
        targetRevision: master
        path: "{{path}}"
      destination:
        server: cluster-server
        namespace: argocd
