apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: api
spec:
  generators:
    - list:
        elements:
          - cluster: dev
            url: https:dev.com
          - cluster: qa
            url: https://qa.com
          - cluster: prod
            url: https://prod.com
  template:
    metadata:
      name: "{{cluster}}-api"
    spec:
      project: default
      source:
        repoURL: https://github.com/doniyorniazov/kubernetes
        targetRevision: master
        path: k8s/environments/*
      destination:
        server: "{{url}}"
        namespace: bgd
