name: Release 

on:
  workflow_call:
    inputs:
      image_name: 
        required: true
        type: string
      tag:
        type: string
      test:
        
    secrets:
      registry-username: 
        required: true
      registry-passwrod: 
        required: true

steps: 
  - uses: actions/checkout@2

  - name: Setup BuildX
    uses: docker/setup-buildx-action@1

  - name: Login to the Registry
    uses: docker/login-action@1
    with:
      username: ${{secrets.registry-username}}
      password: ${{secrets.registry-password}}

  - name: Set the tag
    run: |
      if[ -z "${{inputs.tag}}" ]
      then 
        echo "final-tag=latest" >> $GITHUB_ENV
      else
        echo "final_tag=${{inputs.tag}}" >> $GITHUB_ENV
      fi

  - name: Build and Push the Image 
    uses: docker/build-push-action@v2
    with:
      context: .
      push: true
      tags: ${{}}
      
