apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: simpleapi
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            cluster: main #label the cluster secret cluster=main
  template:
    metadata:
      name: "{{cluster}}-api"
    spec:
      project: default
      source:
        repoURL: https://github.com/doniyorniazov/refit-test
        targetRevision: master
        path: k8s/environments/dev
      destination:
        server: "{{url}}"
        namespace: argocd
