apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simpleapi-pv
  namespace: utilities
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: simpleapi-pv
  resources:
    requests:
      storage: 10Gi
