apiVersion: v1
kind: Service
metadata:
  name: dev-simpleapi-erp
  namespace: api
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: simpleapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-simpleapi-erp
spec:
  selector:
    matchLabels:
      app: simpleapi
  template:
    metadata:
      labels:
        app: simpleapi
    spec:
      containers:
        - image: hub.docker.com/niazovd/api:v1
          name: simpleapi
          ports:
            - containerPort: 8002
              name: http
              protocol: TCP
