apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
namePrefix: prod-
resources:
  - image.yml
# Running command to update kustomize build overlays/dev > overlays/prod/image.yml
