apiVersion: v1
kind: Service
metadata:
  name: simpleapi
  namespace: api
spec:
  type: LoadBalancer
  ports:
    - port: 80 #this  port is the port which belongs to ClusterIP which will be exposed
      targetPort: 80 #this port should match with the port application is targetting in this case: containerPort: 80.
      protocol: TCP
  selector:
    app: simpleapi
