name: Docker Image CI

on:
  workflow_dispatch:
  
jobs:
  build:
    name: Build & push docker image
    runs-on: ubuntu-latest
    env:
      IMG_NAME: niazovd/api

    steps:
    - uses: actions/checkout@v3    

    - name: Docker metadata
      id: metadata
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.IMG_NAME }}
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=raw,value={{sha}},enable=${{ github.ref_type != 'tag' }}
          
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./api
        push: ${{ 
          github.event.base_ref =='refs/heads/main' && 
          github.ref_type == 'tag' && 
          !startsWith(github.ref, 'refs/tags/v0.') }}
        tags: |
          ${{ steps.metadata.outputs.tags }}
          latest
        labels: ${{ steps.metadata.outputs.labels }}  


